base_path: data/toy_objects/*/
baseshape_path: data/basicshapes
num_frames: 64
resolution: [512, 512]
spp: 64
envlight: data/envmaps
env_scale: 1.0
use_denoise: OPTIX
bg_color: [0, 0, 0]
dump_alpha: true
dump_envmap: false
dump_ball_env: false
dump_env_bg: false
transparent_bg: true
num_lighting: 2
random_env_rotation: true
random_env_flip: true
random_env_scale: [0.7, 1.4]
video_mode: drop_phy
num_rendering: 2
cam_phi_range: [60, 120]
cam_theta_range: [5, 50]
cam_t_range: [0, 0]
fov_range: [45, 45]
radius_range: [3.0, 3.5]
glbs_per_scene: 3
glbs_scale_range: [0.6, 0.8]
glbs_rotation_range: [-45, 45]
glbs_placement_bbox: [-1.0, -1.0, 1.0, 1.0]
glbs_rescale: true
placement_plane: data/plane_basic
placement_plane_textures: data/textures
texture_sample_weight: null
placement_bbox_scale: 1.1
placement_plane_offset: [0, 0, -0.5]
placement_plane_scale: 10
placement_bbox: [-1.5, -1.5, 1.5, 1.5]
placement_grid_res: [40, 40]
shapes_per_scene: 2
sample_shape_texture: false
dump_complete: false
dump_blend: true

spawn:
  region:
    center: [0.0, 0.0, 1.5]
    size: [1.0, 1.0, 0.6]
  min_separation: 0.06
  retries: 50

initial_motion:
  speed_range: [0.0, 3.0]
  downward_bias: 0.7
  angular_speed_range: [0.0, 30.0]

physics:
  gravity: [0.0, 0.0, -9.81]
  steps_per_second: 240
  substeps_per_frame: 5
  solver_iterations: 20
  split_impulse: true
  collision_shape: CONVEX_HULL
  collision_margin: 0.0001
  restitution_range: [0.1, 0.6]
  friction_range: [0.3, 0.9]
  use_deactivation: true
  set_rigidbody_plane: false
  mass: 1.0

environment:
  ground_size: 10.0
  walls:
    enabled: true
    size: [6.0, 6.0]
    height: 2.0





